# Generated by Django 3.2.8 on 2021-10-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingunit',
            name='date_entered',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='entered_by_user',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='lat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='long',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='polling_unit_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='polling_unit_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='polling_unit_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='uniquewardid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='user_ip_address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
